# Generated by Django 4.0.4 on 2022-05-20 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='math_class',
            new_name='study_class',
        ),
    ]
